### ISSUE TITLE
Support/Check the operation with ROS 2 Iron Irwini

### ISSUE THREAD

**Issue by takasehideki** [mROS-base/mros2-esp32#2]
Happy World Turtle Day! The new ROS 2 Release "Iron Irwimi" has come!
https://discourse.ros.org/t/ros-2-iron-irwini-released/31553

We need to check the operation with Iron installed on the host, and if it does not work, issues should be clarified and resolved.
Also, ROS 2 Foxy will soon be sunset. If it is difficult to manage the code to support both, we may eliminate the code for Foxy.

**Comment by schtl** [comment]
Are there any news about the iron as host?

**Comment by takasehideki** [comment]
Hi @schtl thank you so much for your comment!
But unfortunately, nothing has happened due to the limitation of our development resources.
If you have enough time with strong interest and motivation, we want you to give it a try as the good first issue. If you observe any problems, please report them to us.

**Comment by takasehideki** [comment]
We couldn't do anything with Iron,,, But it is not so serious because Iron is STS and has already reached its EOL. So I just closed this.
