### ISSUE TITLE
Successfully pub/sub with mros2-esp32 using Seeed Studio XIAO ESP32S3

### ISSUE THREAD

**Issue by yamati-kz** [mROS-base/mros2-esp32#24]
I tried mros2-esp32 on Seeed Studio XIAO ESP32S3, so I'll report on it. This is not an Issues report.
Verification requested by Seeed Studio.
![Screenshot from 2024-08-20 02-53-10](https://github.com/user-attachments/assets/2495b148-d155-4e67-99e5-bf33a78b1001)

Seeed Studio XIAO ESP32S3. ( ESP-IDF v5.4-dev-1832-g23e4823f17 )
NVIDIA Jetson Orin Nano Developer Kit. ( NVIDIA Jetpack 6.0 first production release / Ubuntu 22.04.4 LTS )

mros2-esp32 : Latest version as of August 2, 2024
[mros2-host-examples](https://github.com/mROS-base/mros2-host-examples) : Latest version as of August 2, 2024
[ROS 2 Humble Hawksbill](https://docs.ros.org/en/humble/index.html)

1. The communication log is attached.
![Screenshot from 2024-08-20 02-21-25](https://github.com/user-attachments/assets/1d7aa722-a35a-46ba-81ab-838a7de97789)

![Screenshot from 2024-08-20 02-26-45](https://github.com/user-attachments/assets/1d45f54d-2e8b-43c7-af62-d710ba50ea24)

2. Commands used in Seeed Studio XIAO ESP32S3
```
. $HOME/esp/esp-idf/export.sh
idf.py set-target esp32s3
idf.py menuconfig
idf.py build
sudo chmod 666 /dev/ttyACM0
idf.py -p /dev/ttyACM0 flash
idf.py -p /dev/ttyACM0 monitor
```
3. Seeed Studio XIAO ESP32S3 menuconfig settings
![Screenshot from 2024-08-20 01-22-38](https://github.com/user-attachments/assets/e3ed13f5-2c98-49f9-82dd-009edb524d7c)
![Screenshot from 2024-08-20 01-27-30](https://github.com/user-attachments/assets/77d0cb49-50a7-436b-ab50-3aed9f1dd5f3)

**Comment by yamati-kz** [comment]
![image](https://github.com/user-attachments/assets/55efd6b0-97b8-4fec-9cc3-25128d1beb67)

**Comment by meilily** [comment]
This is superb!! Could you also include XIAO ESP32S3 and XIAO ESP32C6 to [the supported boards](https://github.com/mROS-base/mros2-esp32) in the readme of this repo? Thank you so much!!!!

**Comment by yamati-kz** [comment]
@meilily : Thank you for your message here. Unfortunately, I am not a contributor and cannot rewrite the Readme.

@takasehideki , @s-hosoai : Takase-san and Hosoai-san, I would appreciate it if you could consider this matter.

**Comment by yamati-kz** [comment]
https://x.com/seeedstudio/status/1826175627063603496?s=46&t=4HGyVKsDUAlfHEv_mPnMUw

**Comment by yamati-kz** [comment]
@meilily 
The mros2-esp32 project has been listed in the top README!

**Comment by meilily** [comment]
Thank you so much!
