### ISSUE TITLE
I used Seeed Studio XIAO ESP32C3 and was able to pub/sub.

### ISSUE THREAD

**Issue by yamati-kz** [mROS-base/mros2-esp32#7]
It's a report, not an issue. https://github.com/algyan/XIAOGYAN/discussions/55

Seeed Studio XIAO ESP32C3.
Ubuntu 20.04.6 (JetPack 5.1.1, Nvidia Jetson Xavier NX Developer Kit)

Pub/sub worked directly between two Seeed Studio XIAO ESP32C3s.
Pub/Sub worked directly with Seeed Studio XIAO ESP32C3 and ESP32-DevKitC-32D.

The target when building ESP32-DevKitC-32D is esp32.
I installed [CH340 driver](https://jetsonhacks.com/2018/02/09/install-usb-serial-converter-kernel-modules-l4t-28-1/). to use ESP32-DevKitC-32D with Nvidia jetpack5.1.

**Comment by takasehideki** [comment]
@yamati-kz thank you so much for your fantastic report! 
I added this board as the supported environment by eb64170 🎉 
(this branch will be merged to main soon, I promise)

**Comment by yamati-kz** [comment]
This is the verification result.

https://github.com/algyan/XIAOGYAN/discussions/55
